### ISSUE TITLE
Inquiry: How to modify CW sizes of TL-WDN620 (or other WNIC)

### ISSUE THREAD

**Issue by Farming-King** [QianrenLi/ReinWiFi#1]
Dear all,

Thank you very much for your attention to this issue.

I have read your paper "ReinWiFi: A Reinforcement-Learning-Based Framework for the Application-Layer QoS Optimization of WiFi Networks" (https://arxiv.org/pdf/2405.03526), and I found it very insightful.

I am particularly interested in **understanding **how to implement a Linux module** to adapt the CW sizes of TL-WDN6200 adapters in real-time from user space**.

Could you please share if you used `iwpriv` or any other tools to call functions in **`cfg80211`**?

Your guidance on this matter would be greatly appreciated.

**Comment by QianrenLi** [comment]
Thank you for your interests in this work. And the procedure of implementing a Linux module can be done in following procedures:
1. Extract the pointer address pointed to the adpater struct
2. Borrow CW modification code from the driver itself to the hack module [wlsops-hack](https://github.com/lasso-sustech/wlsops-hack)

As for the "communication" between the CW value from user space to kernel space, the legacy part of the hack module performs this task. Patches for the TL-WDN6200 driver, and the hack module can be found [here](https://github.com/qianrenLi/rtl8812au). I hope this can help.
> Note: TL-WDN6200 might not be the optimal choice if you want to modify CW, since it only provides a limited choice.

**Comment by Farming-King** [comment]
Interesting idea, thanks a lot.

**Comment by QianrenLi** [comment]
If this solves your problem and no futher question, I shall close this issue in 24 hours; If any problem, please let me know.
